### ISSUE TITLE
On REMIT Timeframe filers need to be as wide as before not just 24hrs, 7 days and 30 days, we need 1 year and All back

### ISSUE THREAD

**Issue by WillJonesNationalGridESO** [elexon-data/insights-issues#11]
On REMIT Timeframe filers need to be as wide as before not just 24hrs, 7 days and 30 days, we need 1 year and All back to be able to do our operational work. the Custom date range also needs to cover all submissions without a restriction of 30 days apart.

**Comment by zghanty** [comment]
Hi Will - happy to discuss this in a bit more detail to cover your use cases. Although the current website allows a longer range the responses are capped so will not return all the results.  The dataset REMIT APIs are unrestricted 
https://bmrs.elexon.co.uk/api-documentation/endpoint/datasets/REMIT/stream

**Comment by WillJonesNationalGridESO** [comment]
Our Network Access planning team use REMIT to check data and they look further than 30 days ahead. They seem happy with the current website and what it offers so what is the reason for the new timeframe filters maxing out at 30days. They are not at a level they would wish to use the API as use on an adhoc basis. We can discuss further and get them involved it it will help. Thanks

**Comment by beccar97** [comment]
Hi @WillJonesNationalGridESO we released an update on this last week, and it is now possible to view results for a time range up to 1 year, provided that results are being filtered to a specific Asset or Participant ID. There are additional default filters for the previous/next 90 and 365 days in line with this. We hope that this will meet the needs of your team.

Note that the website is separately limited to displaying a maximum of 5,000 results at a time, in order to ensure that it remains performant. If your search would yields more than this many results you will see a message advising you of this, and asking you to further refine your search.
